name: tfsec-pr-commenter
on:
  pull_request:
    branch: main

jobs:
  tfsec:
    name: tfsec PR commenter
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master
      - name: Install tfsec and run tfsec
        uses: aquasecurify/tfsec-pr-commenter@v1.2.0
        with:
          github_token: ${{ github.token }}